/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-14 12:39:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import td.kits3.livedinner.dao.ContactDAO;
import tp.kits3.livedinner.io.Contact;
import java.util.List;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("tp.kits3.livedinner.io.Contact");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("td.kits3.livedinner.dao.ContactDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    	String contextPath = request.getContextPath();
    	//System.out.println(contextPath);
    	ContactDAO dao = new ContactDAO();
    	//Contact contact = new Contact();
    	List<Contact> list = (List<Contact>)request.getAttribute("ContactList");
    	ServletContext cxv = request.getServletContext();
    	//contact = (Contact) cxv.getAttribute("ContactFind");
    	List<Contact> listCT = (List<Contact>) cxv.getAttribute("ContactFind");
    	System.out.println(listCT);
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\"><!-- Basic -->\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">   \r\n");
      out.write("   \r\n");
      out.write("    <!-- Mobile Metas -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" \r\n");
      out.write("     <!-- Site Metas -->\r\n");
      out.write("    <title>Live Dinner Restaurant</title>  \r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Site Icons -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print(contextPath );
      out.write("/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=");
      out.print(contextPath );
      out.write("\"images/apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Site CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/css/style.css\">    \r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Start header -->\r\n");
      out.write("\t<header style = \"position: fixed;\">\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<a href=\"index.html\">\r\n");
      out.write("\t\t\t\t\t<img src=\" ");
      out.print(contextPath );
      out.write("/images/logo.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<button type=\"button\" data-toggle=\"collapse\" data-target=\"#navbars-rs-food\" aria-controls=\"navbars-rs-food\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t  <span>Search</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div id=\"navbars-rs-food\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"active\" href=\"/jdbc1/\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Menu</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li >\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" id=\"dropdown-a\" onclick=\"show('subPage')\" data-toggle=\"dropdown\">Pages</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"subPage\" class=\"drop-menu\" aria-labelledby=\"dropdown-a\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"reservation.html\">Reservation</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"stuff.html\">Stuff</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"gallery.html\">Gallery</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" id=\"dropdown-a\" onclick=\"show('subBlog')\" data-toggle=\"dropdown\">Blog</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div id = \"subBlog\" class=\"drop-menu\" aria-labelledby=\"dropdown-a\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"blog.html\">blog</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"blog-details.html\">Blog Single</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- End header -->\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Contact -->\r\n");
      out.write("\t<div class=\"contact-box-start\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-title\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Contact</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap-form\">\r\n");
      out.write("\t\t\t\t\t<form id=\"contactForm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wrap-sub-form\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap wrap-user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\" box user-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tUsename: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"name\" name=\"name\" placeholder=\"Your Name\" required data-error=\"Please enter your name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                                 \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap  wrap-phone\">\r\n");
      out.write("\t\t\t\t\t\t\t\tPhoneNumber: \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box phone-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"phone\" id=\"priphone\" name=\"priphone\" placeholder=\"Your Phone\" required data-error=\"Please enter your priphone\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"phone\" id=\"subphone\" name=\"subphone\" placeholder=\"Your Phone\" data-error=\"Please enter your subphone\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                                 \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap  wrap-mail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box email-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tEmail: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Your Email\" id=\"email\" name=\"name\" required data-error=\"Please enter your email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap  wrap-address\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box address-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAddress: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Your address\" id=\"address\" name=\"address\" required data-error=\"Please enter your email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap  wrap-check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box check-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCheckbox\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"unused\" name=\"unused\"  data-error=\"Please enter your check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap  wrap-opening\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box opening-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tOpening: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Your opening\" id=\"opening\" name=\"opening\" required data-error=\"Please enter your opening\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap  wrap-weekday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box weekday-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tWeekday: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Your weekday\" id=\"weekday\" name=\"weekday\" required data-error=\"Please enter your weekday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap wrap-weekend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box weekend-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Your weekend\" id=\"weekend\" name=\"weekend\" required data-error=\"Please enter your weekend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap  wrap-aboutus\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box aboutus-box\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\tAbout Us: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea id=\"aboutus\" placeholder=\"Your Message\" rows=\"4\" data-error=\"Write your message\" required></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap  wrap-latitude\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box latitude-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tLatitude: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Your latitude\" id=\"latitude\" name=\"latitude\" required data-error=\"Please enter your latitude\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Your logitude\" id=\"logitude\" name=\"logitude\" required data-error=\"Please enter your logitude\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"wrap  wrap-submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"box submit-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <input type=\"submit\" name=\"submit\" value=\"Update\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>            \r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Contact -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Contact info -->\r\n");
      out.write("\t<div class=\"contact-box\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\" >\r\n");
      out.write("\t\t\t\t<div class=\"wrap-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"mof-fa fa fa-volume-control-phone\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t<div class=\" wrap-common wrap-phone \">\r\n");
      out.write("\t\t\t\t\t\t<h4>Phone</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>+ \r\n");
      out.write("\t\t\t\t\t\t");
      out.print(list.get(0).getPriphone()+
							list.get(0).getSubphone()
						);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<i class=\"mof-arrow fa fa-angle-double-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"wrap-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"mof-fa fa fa-envelope\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t<div class=\" wrap-common wrap-email\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Email</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(list.get(0).getEmail() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<i class=\"mof-arrow fa fa-angle-double-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"wrap-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"mof-fa fa fa-map-marker\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t<div class=\" wrap-common wrap-location\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Location</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(list.get(0).getLatitude() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t, Lorem Street, US\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Contact info -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Footer -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t\t<div >\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h3>About Us</h3>\r\n");
      out.write("\t\t\t\t\t<p>Integer cursus scelerisque ipsum id efficitur. Donec a dui fringilla, gravida lorem ac, semper magna. Aenean rhoncus ac lectus a interdum. Vivamus semper posuere dui.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h3>Subscribe</h3>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"EMAIL\" id=\"subs-email\" placeholder=\"Email Address...\" type=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" >SUBSCRIBE</button>\r\n");
      out.write("\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h3>Contact information</h3>\r\n");
      out.write("\t\t\t\t\t<p>Ipsum Street, Lorem Tower, MO, Columbia, 508000</p>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\">+01 2000 800 9999</a></p>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\"> info@admin.com</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h3>Opening hours</h3>\r\n");
      out.write("\t\t\t\t\t<p><span>Monday: </span>Closed</p>\r\n");
      out.write("\t\t\t\t\t<p><span>Tue-Wed :</span> 9:Am - 10PM</p>\r\n");
      out.write("\t\t\t\t\t<p><span>Thu-Fri :</span> 9:Am - 10PM</p>\r\n");
      out.write("\t\t\t\t\t<p><span>Sat-Sun :</span> 5:PM - 10PM</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div >\r\n");
      out.write("\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<p>All Rights Reserved. &copy; 2018 <a href=\"#\">Live Dinner Restaurant</a> Design By : \r\n");
      out.write("\t\t\t\t\t<a href=\"#\">html design</a></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- End Footer -->\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"#\" id=\"back-to-top\" title=\"Back to top\" style=\"display: none;\"><i aria-hidden=\"true\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ALL JS FILES -->\r\n");
      out.write("    <!-- ALL PLUGINS -->\r\n");
      out.write("    <script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
