/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-14 11:18:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import tp.kits3.livedinner.io.Menu;

public final class menulist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    	// fields and methods
    	//JSP compile as Servlet
    	
    	//int version = 1; //<-field of Sample.class
    	// private void todo(){ //<-method of Sample.class
    		
    	//}
    
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("tp.kits3.livedinner.io.Menu");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    	//expression : noi dung se dc thuc hien - java code
    	//request.getAttribute("pm"); // from Servlet
    	//request.getParameter("tgname"); //from client
    	
    	//JSP is class type Servlet
    	String contextPath = request.getContextPath(); //or pageContext
    	List<Menu> menulist = (List<Menu>) request.getAttribute("MenuList");
    	int lenght = menulist.size();
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\"><!-- Basic -->\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">   \r\n");
      out.write("   \r\n");
      out.write("    <!-- Mobile Metas -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" \r\n");
      out.write("     <!-- Site Metas -->\r\n");
      out.write("    <title>Live Dinner Restaurant</title>  \r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Site Icons -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print( contextPath );
      out.write("/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"images/apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Site CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( contextPath );
      out.write("/css/style.css\">    \r\n");
      out.write("    <!-- Custom CSS for each page -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( contextPath );
      out.write("/css/custom.css\">\r\n");
      out.write("\t<!-- Font awesome css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Start header -->\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<a href=\"index.html\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print( contextPath );
      out.write("/images/logo.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<button type=\"button\" data-toggle=\"collapse\" data-target=\"#navbars-rs-food\" aria-controls=\"navbars-rs-food\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t  <span>Search</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div id=\"navbars-rs-food\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"active\" href=\"/jdbc1/\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/jdbc1/menu/list\">Menu</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li >\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" id=\"dropdown-a\" onclick=\"show('subPage')\" data-toggle=\"dropdown\">Pages</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"subPage\" class=\"drop-menu\" aria-labelledby=\"dropdown-a\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"reservation.html\">Reservation</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"stuff.html\">Stuff</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"gallery.html\">Gallery</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" id=\"dropdown-a\" onclick=\"show('subBlog')\" data-toggle=\"dropdown\">Blog</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div id = \"subBlog\" class=\"drop-menu\" aria-labelledby=\"dropdown-a\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"blog.html\">blog</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"blog-details.html\">Blog Single</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(contextPath );
      out.write("/contact/list\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- End header -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start slides -->\r\n");
      out.write("\t<input id=\"check1\" name=\"slide-radio\" type=\"radio\" checked=\"checked\">\r\n");
      out.write("\t<input id=\"check2\" name=\"slide-radio\" type=\"radio\">\r\n");
      out.write("\t<input id=\"check3\" name=\"slide-radio\" type=\"radio\">\r\n");
      out.write("\t<div id=\"slides\">\r\n");
      out.write("\t\t<ul class=\"slide-wrap\">\r\n");
      out.write("\t\t\t<li class=\"fade\">\r\n");
      out.write("\t\t\t\t<img src=\"images/slider-01.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap-text\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sub-wrap-text container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"last-sub-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1 ><strong>Welcome To <br> Live Dinner Restaurant</strong></h1>\r\n");
      out.write("\t\t\t\t\t\t\t<p >See how your users experience your website in realtime or view  <br> \r\n");
      out.write("\t\t\t\t\t\t\ttrends to see any changes in performance over time.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p><a href=\"#\">Reservation</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"fade\">\r\n");
      out.write("\t\t\t\t<img src=\"images/slider-02.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap-text\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sub-wrap-text container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"last-sub-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1 ><strong>Welcome To <br> Live Dinner Restaurant</strong></h1>\r\n");
      out.write("\t\t\t\t\t\t\t<p >See how your users experience your website in realtime or view  <br> \r\n");
      out.write("\t\t\t\t\t\t\ttrends to see any changes in performance over time.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"btn-reservation\"><a href=\"#\">Reservation</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"fade\">\r\n");
      out.write("\t\t\t\t<img src=\"images/slider-03.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap-text\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sub-wrap-text container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"last-sub-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1 ><strong>Welcome To <br> Yamifood Restaurant</strong></h1>\r\n");
      out.write("\t\t\t\t\t\t\t<p >See how your users experience your website in realtime or view  <br> \r\n");
      out.write("\t\t\t\t\t\t\ttrends to see any changes in performance over time.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p><a href=\"#\">Reservation</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul class=\"slide-paging\" >\r\n");
      out.write("\t\t\t<li class=\"paging1\" onclick=\"changeDot(1)\">\r\n");
      out.write("\t\t\t\t<label for=\"check1\">\r\n");
      out.write("\t\t\t\t\t<span class=\"disc\"></span>\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"paging2\" onclick=\"changeDot(2)\">\r\n");
      out.write("\t\t\t\t<label for=\"check2\">\r\n");
      out.write("\t\t\t\t\t<span class=\"disc\" ></span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"paging3\" onclick=\"changeDot(3)\">\r\n");
      out.write("\t\t\t\t<label for=\"check3\">\r\n");
      out.write("\t\t\t\t\t<span class=\"disc\"></span>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"slides-navigation\">\r\n");
      out.write("\t\t\t<a class=\"prev\" href=\"#\" onclick=\"activeChange(-1)\"><i class=\"fa fa-angle-left\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t<a class=\"next\" href=\"#\" onClick=\"activeChange(1)\"><i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End slides -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Start All Pages -->\r\n");
      out.write("\t");
for(Menu menu : menulist) {
      out.write(" \r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t\t<div >\r\n");
      out.write("\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t<h1>hddgfdgfdgfdg</h1>\r\n");
      out.write("\t\t\t\t\t<h1>");
      out.print( menu.getMuname());
      out.write("></h1>\r\n");
      out.write("\t\t\t\t\t<p>");
      out.print( menu.getDetails());
      out.write("></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- End All Pages -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start About -->\r\n");
      out.write("\t<div id=\"about-cnt\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap-text\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sub-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<h1>Welcome To <span>Live Dinner Restaurant</span></h1>\r\n");
      out.write("\t\t\t\t\t\t<h4>Little Story</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque auctor suscipit feugiat. Ut at pellentesque ante, sed convallis arcu. Nullam facilisis, eros in eleifend luctus, odio ante sodales augue, eget lacinia lectus erat et sem. </p>\r\n");
      out.write("\t\t\t\t\t\t<p>Sed semper orci sit amet porta placerat. Etiam quis finibus eros. Sed aliquam metus lorem, a pellentesque tellus pretium a. Nulla placerat elit in justo vestibulum, et maximus sem pulvinar.</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">Reservation</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"wrap-img\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/about-img.jpg\" alt=\"\" >\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End About -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start QT -->\r\n");
      out.write("\t<div class=\"qt-wrap\">\r\n");
      out.write("\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\" If you're not the one cooking, stay out of the way and compliment the chef. \"\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<span>Michael Strahan</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End QT -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Menu -->\r\n");
      out.write("\t<div class=\"menu-box\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-title\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Special Menu</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"side-left\">\r\n");
      out.write("\t\t\t\t\t<div id=\"v-pills-tab\" role=\"tablist\" aria-orientation=\"vertical\" class=\"wrap-pills-tab\">\r\n");
      out.write("\t\t\t\t\t\t<a id=\"v-pills-home-tab\" onclick=\"sideMenu('v-pills-home')\" data-toggle=\"pill\"  role=\"tab\" aria-controls=\"v-pills-home\" aria-selected=\"true\">All</a>\r\n");
      out.write("\t\t\t\t\t\t<a id=\"v-pills-profile-tab\" onclick=\"sideMenu('v-pills-profile')\" data-toggle=\"pill\"  role=\"tab\" aria-controls=\"v-pills-profile\" aria-selected=\"false\">Drinks</a>\r\n");
      out.write("\t\t\t\t\t\t<a id=\"v-pills-messages-tab\" onclick=\"sideMenu('v-pills-messages')\" data-toggle=\"pill\" role=\"tab\" aria-controls=\"v-pills-messages\" aria-selected=\"false\">Lunch</</a>\r\n");
      out.write("\t\t\t\t\t\t<a id=\"v-pills-settings-tab\" onclick=\"sideMenu('v-pills-settings')\" data-toggle=\"pill\"  role=\"tab\" aria-controls=\"v-pills-settings\" aria-selected=\"false\">Dinner</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"side-right\">\r\n");
      out.write("\t\t\t\t\t<div id=\"v-pills-tabContent\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"v-pills-home\"  role=\"tabpanel\" aria-labelledby=\"v-pills-home-tab\" class=\"wrap-pills\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-01.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Drinks 1</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $7.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-02.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Drinks 2</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $9.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-03.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Drinks 3</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $10.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-04.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Lunch 1</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $15.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-05.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Lunch 2</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $18.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-06.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Lunch 3</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $20.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-07.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Dinner 1</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $25.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-08.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Dinner 2</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $22.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-09.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Dinner 3</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $24.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"v-pills-profile\"  role=\"tabpanel\" aria-labelledby=\"v-pills-profile-tab\" class=\"wrap-pills\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-01.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Drinks 1</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $7.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div  class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-02.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Drinks 2</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $9.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-03.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Drinks 3</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $10.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"v-pills-messages\"  role=\"tabpanel\" aria-labelledby=\"v-pills-messages-tab\" class=\"wrap-pills\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-04.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Lunch 1</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $15.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-05.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Lunch 2</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $18.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-06.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Lunch 3</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $20.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"v-pills-settings\"  role=\"tabpanel\" aria-labelledby=\"v-pills-settings-tab\" class=\"wrap-pills\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-07.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Dinner 1</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $25.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-08.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Dinner 2</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $22.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"special-div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub-gallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/img-09.jpg\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrap-detail-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>Special Dinner 3</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Sed id magna vitae eros sagittis euismod.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5> $24.79</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Menu -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Gallery -->\r\n");
      out.write("\t<div class=\"gallery-box\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-title\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Gallery</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap-img-gal\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-box-gal\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-img-01.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/gallery-img-01.jpg\" alt=\"Gallery Images\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-box-gal\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-img-02.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/gallery-img-02.jpg\" alt=\"Gallery Images\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-box-gal\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-img-03.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/gallery-img-03.jpg\" alt=\"Gallery Images\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-box-gal\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-img-04.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/gallery-img-04.jpg\" alt=\"Gallery Images\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-box-gal\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-img-05.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/gallery-img-05.jpg\" alt=\"Gallery Images\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-box-gal\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-img-06.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/gallery-img-06.jpg\" alt=\"Gallery Images\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Gallery -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Customer Reviews -->\r\n");
      out.write("\t<div class=\"customer-box\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-title\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Customer Reviews</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"main-wrap-cus\">\r\n");
      out.write("\t\t\t\t\t<div id=\"reviews\" data-ride=\"carousel\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slider-wrap-cus\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sub-wrap-cus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"img-wrap-cus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/quotations-button.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5><strong >Paul Mitchel</strong></h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>Web Developer</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sub-wrap-cus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"img-wrap-cus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/quotations-button.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5><strong>Steve Fonsi</strong></h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>Web Designer</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sub-wrap-cus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"img-wrap-cus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/quotations-button.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5><strong >Daniel vebar</strong></h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>Seo Analyst</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a  class=\"prev\" href=\"#reviews\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t\t\t\t<span >Previous</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"next\" href=\"#reviews\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>Next</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Customer Reviews -->\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Contact info -->\r\n");
      out.write("\t<div class=\"contact-box\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\" >\r\n");
      out.write("\t\t\t\t<div class=\"wrap-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"mof-fa fa fa-volume-control-phone\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t<div class=\" wrap-common wrap-phone \">\r\n");
      out.write("\t\t\t\t\t\t<h4>Phone</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t+01 123-456-4590\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<i class=\"mof-arrow fa fa-angle-double-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"wrap-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"mof-fa fa fa-envelope\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t<div class=\" wrap-common wrap-email\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Email</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tyourmail@gmail.com\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<i class=\"mof-arrow fa fa-angle-double-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"wrap-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"mof-fa fa fa-map-marker\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t<div class=\" wrap-common wrap-location\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Location</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t800, Lorem Street, US\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Contact info -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Footer -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap-items\">\r\n");
      out.write("\t\t\t\t\t<h3>About Us</h3>\r\n");
      out.write("\t\t\t\t\t<p>Integer cursus scelerisque ipsum id efficitur. Donec a dui fringilla, gravida lorem ac, semper magna. Aenean rhoncus ac lectus a interdum. Vivamus semper posuere dui.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"wrap-items\">\r\n");
      out.write("\t\t\t\t\t<h3>Subscribe</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-form\">\r\n");
      out.write("\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"EMAIL\" id=\"subs-email\" placeholder=\"Email Address...\" type=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" >SUBSCRIBE</button>\r\n");
      out.write("\t\t\t\t\t\t\t<div ></div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"wrap-items\">\r\n");
      out.write("\t\t\t\t\t<h3>Contact information</h3>\r\n");
      out.write("\t\t\t\t\t<p>Ipsum Street, Lorem Tower, MO, Columbia, 508000</p>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\">+01 2000 800 9999</a></p>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\"> info@admin.com</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"wrap-items\">\r\n");
      out.write("\t\t\t\t\t<h3>Opening hours</h3>\r\n");
      out.write("\t\t\t\t\t<p><span>Monday: </span>Closed</p>\r\n");
      out.write("\t\t\t\t\t<p><span>Tue-Wed :</span> 9:Am - 10PM</p>\r\n");
      out.write("\t\t\t\t\t<p><span>Thu-Fri :</span> 9:Am - 10PM</p>\r\n");
      out.write("\t\t\t\t\t<p><span>Sat-Sun :</span> 5:PM - 10PM</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap-bottom\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<p>All Rights Reserved. &copy; 2018 <a href=\"#\">Live Dinner Restaurant</a> Design By : \r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">html design</a></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- End Footer -->\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"#\" id=\"back-to-top\" title=\"Back to top\" style=\"display: none;\"><i aria-hidden=\"true\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ALL JS FILES -->\r\n");
      out.write("\t<!-- ALL PLUGINS -->\r\n");
      out.write("    <script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
